public class CatchingExeptions {

	public static void main(String[] args) {
		
		try {
			int[] a = new int[2];
			
			a[0] = 1;
			
			a[3] = 5;
			
			int b = a[1] / 0;
			
			System.out.println(b);
			
			
		} catch (ArrayIndexOutOfBoundsException exception) {
			System.out.println("You are trying to access non-existing index.");
		}  catch (Exception exception){
			System.out.println("Another error!");
		}

	}

}
