package Exceptions;

public class ThrowingException {

	public static void main(String[] args) {
		
		Person person = new Person(12);
		
		try {
			person.setAge(-11);
			
			System.out.println("Ð’ÑŠÐ·Ñ€Ð°Ñ?Ñ‚: " + person.getAge());
		} catch (IllegalArgumentException exception) {
			System.out.println("Ð’ÑŠÐ·Ð½Ð¸ÐºÐ½Ð° Ð³Ñ€ÐµÑˆÐºÐ°: " + exception.getMessage());
		}

	}

}

class Person {

	private String name;
	
	private int age;
	
	public Person() {
		super();
	}
	s
	public Person(String name, int age) {
		super();
		this.name = name;
		this.age = age;
	}
	
	public String getName() {
		return name;
	}
	
	public void setName(String name) {
		this.name = name;
	}
	
	public int getAge() {
		return age;
	}
	
	public void setAge(int age) {
		
		if(age < 0){
			throw new IllegalArgumentException("Age cannot be negative!");
		}
		
		this.age = age;
	}


}
